let movies=[],current=null,rank="A";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let watched=JSON.parse(localStorage.getItem("movie.v2.watched")||"[]"),wish=JSON.parse(localStorage.getItem("movie.v2.wish")||"[]");
fetch("movies.json").then(r=>r.json()).then(d=>{movies=d;init()}).catch(()=>alert("movies.jsonを読み込めません。GitHub Pages上で開いてください。"));
function fill(el,a){el.innerHTML=a.map(x=>`<option value="${x}">${x}</option>`).join("")}
function init(){fill($("#category"),["すべて","ハリウッド映画","邦画","アニメ映画"]);fill($("#genre"),["すべて",...[...new Set(movies.flatMap(x=>x.genres))].sort()]);fill($("#service"),["すべて","Netflix","Disney+","Hulu","配信確認済み"]);render()}
function filtered(){const c=$("#category").value,g=$("#genre").value,s=$("#service").value;return movies.filter(m=>(c==="すべて"||m.category===c)&&(g==="すべて"||m.genres.includes(g))&&(s==="すべて"||(s==="配信確認済み"?m.verified:m.services.includes(s))))}
function rnd(a){return a[Math.floor(Math.random()*a.length)]}
function reelText(el,m,mode){el.className="reel "+mode;el.querySelector(".strip").innerHTML=`${m.icon}<b>${m.title}</b>`}
function spin(){const p=filtered();if(!p.length)return alert("この組み合わせで登録済みの作品がありません。ジャンルか配信条件を広げてください。");$("#result").classList.add("hidden");let n=0;const reels=[$("#r1"),$("#r2"),$("#r3")];reels.forEach(r=>r.className="reel spinfast");
let timer=setInterval(()=>{reels.forEach((r,i)=>reelText(r,rnd(p),n<12?"spinfast":n<20?"spinmed":"spinslow"));n++;if(n===13)reels[0].className="reel spinmed";if(n===18)reels[1].className="reel spinmed";if(n>24){clearInterval(timer);current=rnd(p);setTimeout(()=>{reelText(reels[0],current,"");reels[0].animate([{transform:"translateY(-8px)"},{transform:"translateY(0)"}],{duration:160,easing:"steps(3)"})},120);setTimeout(()=>{reelText(reels[1],current,"");reels[1].animate([{transform:"translateY(-8px)"},{transform:"translateY(0)"}],{duration:160,easing:"steps(3)"})},340);setTimeout(()=>{reelText(reels[2],current,"");reels[2].animate([{transform:"translateY(-8px)"},{transform:"translateY(0)"}],{duration:160,easing:"steps(3)"});show(current)},600)}},65)}
function show(m){$("#title").textContent=m.title;$("#categoryTag").textContent=m.category;$("#icon").textContent=m.icon;$("#hook").textContent=m.hook;$("#tags").innerHTML=m.genres.map(x=>`<span class="tag">${x}</span>`).join("");$("#services").innerHTML=m.services.length?m.services.map(x=>`<span class="service">${x} ✓ 2026-09-06確認</span>`).join(""):`<span class="tag">配信先：未確認</span>`;$("#wish").textContent=wish.some(x=>x.title===m.title)?"★ 観たい済み":"☆ 観たい";$("#result").classList.remove("hidden")}
function saveAll(){localStorage.setItem("movie.v2.watched",JSON.stringify(watched));localStorage.setItem("movie.v2.wish",JSON.stringify(wish));render()}
function esc(s){return String(s||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
function render(){$("#stats").textContent=`${movies.length||300} TITLES / ${watched.length} WATCHED`;$("#watchList").innerHTML=wish.length?wish.map((m,i)=>`<div class="card"><b>${esc(m.title)}</b><br><small>${m.category} / ${m.genres.join("・")}</small><div class="actions"><button onclick="reviewWish(${i})">観た</button><button onclick="removeWish(${i})">削除</button></div></div>`).join(""):"<p>まだありません。</p>";$("#historyList").innerHTML=watched.length?watched.map(m=>`<div class="card"><b>${esc(m.title)}</b> <span class="tag">${m.rank}</span><br><small>${esc(m.category)} / ${esc(m.date)}</small>${m.memo?`<p>${esc(m.memo)}</p>`:""}</div>`).join(""):"<p>まだありません。</p>"}
$("#spin").onclick=spin;$("#again").onclick=spin;$("#wish").onclick=()=>{if(!current)return;wish.some(x=>x.title===current.title)?wish=wish.filter(x=>x.title!==current.title):wish.unshift(current);saveAll();show(current)};$("#watched").onclick=()=>openReview(current);
function openReview(m){if(!m)return;current=m;rank="A";$("#reviewTitle").textContent=`「${m.title}」の評価`;$("#memo").value="";$$(".ranks button").forEach(b=>b.classList.toggle("active",b.textContent==="A"));$("#modal").classList.remove("hidden")}
window.reviewWish=i=>openReview(wish[i]);window.removeWish=i=>{wish.splice(i,1);saveAll()};
$$(".ranks button").forEach(b=>b.onclick=()=>{rank=b.textContent;$$(".ranks button").forEach(x=>x.classList.toggle("active",x===b))});$("#cancel").onclick=()=>$("#modal").classList.add("hidden");$("#save").onclick=()=>{watched=watched.filter(x=>x.title!==current.title);watched.unshift({...current,rank,memo:$("#memo").value.trim(),date:new Date().toLocaleDateString("ja-JP")});wish=wish.filter(x=>x.title!==current.title);$("#modal").classList.add("hidden");saveAll()};
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$(".screen").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active")});
