let movies=[],current=null,rank="A";const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];let watched=JSON.parse(localStorage.getItem("movie.watched")||"[]"),wish=JSON.parse(localStorage.getItem("movie.wish")||"[]");
fetch("movies.json").then(r=>r.json()).then(data=>{movies=data;init()}).catch(()=>alert("movies.jsonを読み込めませんでした。GitHub Pagesまたはローカルサーバー上で開いてください。"));
function init(){fill($("#category"),["すべて",...new Set(movies.map(x=>x.category))]);fill($("#genre"),["すべて",...[...new Set(movies.flatMap(x=>x.genres))].sort()]);fill($("#service"),["すべて",...new Set(movies.flatMap(x=>x.services))]);render()}
function fill(el,a){el.innerHTML=a.map(x=>`<option>${x}</option>`).join("")}function pool(){let c=$("#category").value,g=$("#genre").value,s=$("#service").value;return movies.filter(m=>(c==="すべて"||m.category===c)&&(g==="すべて"||m.genres.includes(g))&&(s==="すべて"||m.services.includes(s)))}function rnd(a){return a[Math.floor(Math.random()*a.length)]}
function spin(){let p=pool();if(!p.length)return alert("条件に合う作品がありません");$$(".reel").forEach(x=>x.classList.add("spinning"));$("#result").classList.add("hidden");let n=0,t=setInterval(()=>{let a=rnd(p),b=rnd(p),c=rnd(p);$("#r1").innerHTML=`${a.icon}<br>${a.genres[0]}`;$("#r2").innerHTML=`${b.icon}<br>${b.category}`;$("#r3").innerHTML=`${c.icon}<br>${c.services[0]}`;if(++n>18){clearInterval(t);current=rnd(p);setTimeout(()=>{$("#r1").innerHTML=`${current.icon}<br>${current.genres[0]}`;$("#r1").classList.remove("spinning")},80);setTimeout(()=>{$("#r2").innerHTML=`${current.icon}<br>${current.category}`;$("#r2").classList.remove("spinning")},250);setTimeout(()=>{$("#r3").innerHTML=`${current.icon}<br>${current.services[0]}`;$("#r3").classList.remove("spinning");show(current)},450)}},70)}
function show(m){$("#icon").textContent=m.icon;$("#title").textContent=m.title;$("#hook").textContent=m.hook;let tags=[m.year||"YEAR TBD",m.category,...m.genres];if(m.verified)tags.unshift("VERIFIED");$("#tags").innerHTML=tags.map((x,i)=>`<span class="tag ${i===0&&m.verified?"verified":""}">${x}</span>`).join("");$("#services").innerHTML=m.services.map(x=>`<span class="service">${x}</span>`).join("");$("#wish").textContent=wish.some(x=>x.title===m.title)?"★ 観たい済み":"☆ 観たい";$("#result").classList.remove("hidden")}
function saveAll(){localStorage.setItem("movie.watched",JSON.stringify(watched));localStorage.setItem("movie.wish",JSON.stringify(wish));render()}
function render(){if(!movies.length)return;$("#count").textContent=`${movies.length} TITLES / ${movies.filter(x=>x.verified).length} VERIFIED`;$("#watchList").innerHTML=wish.length?wish.map((m,i)=>`<div class="card"><b>${m.icon} ${m.title}</b><br><small>${m.category} / ${m.services.join("・")}</small><div class="actions"><button onclick="reviewWish(${i})">観た</button><button onclick="removeWish(${i})">削除</button></div></div>`).join(""):"<p>まだありません。</p>";$("#historyList").innerHTML=watched.length?watched.map(m=>`<div class="card"><b>${m.icon} ${m.title}</b> <span class="tag">${m.rank}</span><br><small>${m.date}</small><p>${esc(m.memo||"")}</p></div>`).join(""):"<p>まだありません。</p>"}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
$("#spin").onclick=spin;$("#again").onclick=spin;$("#wish").onclick=()=>{if(!current)return;wish.some(x=>x.title===current.title)?wish=wish.filter(x=>x.title!==current.title):wish.unshift(current);saveAll();show(current)};$("#watched").onclick=()=>openReview(current);
function openReview(m){if(!m)return;current=m;rank="A";$("#reviewTitle").textContent=m.title;$("#memo").value="";$$(".ranks button").forEach(b=>b.classList.toggle("active",b.textContent==="A"));$("#modal").classList.remove("hidden")}window.reviewWish=i=>openReview(wish[i]);window.removeWish=i=>{wish.splice(i,1);saveAll()};
$$(".ranks button").forEach(b=>b.onclick=()=>{rank=b.textContent;$$(".ranks button").forEach(x=>x.classList.toggle("active",x===b))});$("#cancel").onclick=()=>$("#modal").classList.add("hidden");$("#save").onclick=()=>{watched=watched.filter(x=>x.title!==current.title);watched.unshift({...current,rank,memo:$("#memo").value,date:new Date().toLocaleDateString("ja-JP")});wish=wish.filter(x=>x.title!==current.title);$("#modal").classList.add("hidden");saveAll()};
$$("nav button").forEach(b=>b.onclick=()=>{$$("nav button").forEach(x=>x.classList.remove("active"));b.classList.add("active");$$("section.tab").forEach(x=>x.classList.remove("active"));$("#"+b.dataset.tab).classList.add("active")});
